test_that("readChromatogram.Thermo works", {
  demoRaw <- fs::path_package("extdata", "reserpine07.RAW", package = "MS.Analysis")
  result <- readChromatogram.Thermo(filename = demoRaw, type = "tic", filter = "ms2")
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 1)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 6)
  expect_equal(names(result[[1]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(result[[1]]$info$source, "thermo")
  demoRaw <- fs::path_package("extdata", "reserpine07.RAW", package = "MS.Analysis")
  result <- readChromatogram.Thermo(filename = demoRaw, type = "xic", filter = "ms2",
                                    mz = c(397.16, 448.13), tolerance = 500)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 6)
  expect_equal(names(result[[1]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(result[[1]]$info$source, "thermo")
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_length(result[[1]][["info"]], 6)
  expect_equal(names(result[[1]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(as.character(result[[1]]$info$mz), "397.16")
  expect_equal(names(result[[1]]$data), c("rt", "intensity"))
  expect_equal(nrow(result[[1]]$data), 403)
  expect_equal(as.character(min(result[[1]]$data[,1])), "0.009")
  expect_equal(as.character(max(result[[1]]$data[,1])), "7.00066666666667")
  expect_equal(as.character(min(result[[1]]$data[,2])), "0")
  expect_equal(as.character(max(result[[1]]$data[,2])), "5968176")
  expect_length(result[[2]][["info"]], 6)
  expect_equal(names(result[[2]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(as.character(result[[2]]$info$mz), "448.13")
  expect_equal(names(result[[2]]$data), c("rt", "intensity"))
  expect_equal(nrow(result[[2]]$data), 403)
  expect_equal(as.character(min(result[[2]]$data[,1])), "0.009")
  expect_equal(as.character(max(result[[2]]$data[,1])), "7.00066666666667")
  expect_equal(as.character(min(result[[2]]$data[,2])), "0")
  expect_equal(as.character(max(result[[2]]$data[,2])), "4614730")
})

test_that("readSpectrum.Thermo works", {
  demoRaw <- fs::path_package("extdata", "reserpine07.RAW", package = "MS.Analysis")
  result <- readSpectrum.Thermo(filename = demoRaw, scan = 245, centroided = TRUE)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 1)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 6)
  expect_equal(names(result[[1]]$info), c("source", "filename", "rt", "scan",
                                          "scanType", "centroided"))
  expect_equal(result[[1]]$info$scan, 245)
  expect_equal(names(result[[1]]$data), c("mz", "intensity"))
  expect_equal(nrow(result[[1]]$data), 47)
  expect_equal(as.character(min(result[[1]]$data[,1])), "174.356506347656")
  expect_equal(as.character(max(result[[1]]$data[,1])), "610.101440429688")
  expect_equal(as.character(min(result[[1]]$data[,2])), "2")
  expect_equal(as.character(max(result[[1]]$data[,2])), "5968176")
  result <- readSpectrum.Thermo(filename = demoRaw, scan = 245, centroided = TRUE)
  expect_equal(class(result), "function")
  result <- result(parameters = "extended")
  expect_equal(class(result), "list")
  expect_length(result, 1)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 11)
  expect_equal(names(result[[1]]$info), c('source','filename','rt','scan',
                                          'scanType','centroided','microScanCount',
                                          'ionInjectionTime','elapsedTime',
                                          'resolutionMS','masterScan'))
  expect_equal(as.character(result[[1]]$info$ionInjectionTime), "24.33")
  result <- readSpectrum.Thermo(filename = demoRaw, scan = 245, centroided = TRUE)
  expect_equal(class(result), "function")
  result <- result(parameters = "full")
  expect_equal(class(result), "list")
  expect_length(result, 1)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 25)
  result <- readSpectrum.Thermo(filename = demoRaw, scan = c(245, 246), centroided = TRUE)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 6)
  expect_equal(result[[1]]$info$scan, 245)
  expect_equal(class(result[[2]]), "list")
  expect_length(result[[2]], 2)
  expect_length(result[[2]]$info, 6)
  expect_equal(result[[2]]$info$scan, 246)
  expect_equal(nrow(result[[1]]$data), 47)
  expect_equal(as.character(min(result[[1]]$data[,1])), "174.356506347656")
  expect_equal(as.character(max(result[[1]]$data[,1])), "610.101440429688")
  expect_equal(as.character(min(result[[1]]$data[,2])), "2")
  expect_equal(as.character(max(result[[1]]$data[,2])), "5968176")
  expect_equal(nrow(result[[1]]$data), 47)
  expect_equal(as.character(min(result[[2]]$data[,1])), "173.728240966797")
  expect_equal(as.character(max(result[[2]]$data[,1])), "609.599975585938")
  expect_equal(as.character(min(result[[2]]$data[,2])), "1")
  expect_equal(as.character(max(result[[2]]$data[,2])), "4878015")
})
