test_that("chromatogramInfo.AgilentExport works", {
  result <- chromatogramInfo.AgilentExport("+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "TIC")
  expect_equal(result[1,4], as.numeric(NA))
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("+ESI EIC(485.6975) Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "EIC")
  expect_equal(as.character(result[1,4]), "485.6975")
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("DAD1 - A:Sig=280.0,4.0  Ref=550.0,100.0 Data0001.d")
  expect_equal(names(result), c('signal','scan','wavelength','filename'))
  expect_equal(result[1,1], "DAD1")
  expect_equal(result[1,2], "A:Sig=280.0,4.0")
  expect_equal(as.character(result[1,3]), "280")
  expect_equal(result[1,4], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("BinPump1 - A: Pressure Data0001.d")
  expect_equal(names(result), c('signal','scan','filename'))
  expect_equal(result[1,1], "BinPump1")
  expect_equal(result[1,2], "Pressure")
  expect_equal(result[1,3], "Data0001.d")
})

test_that("readChromatogram.AgilentExport.memory works", {
  demoFile <- fs::path_package("extdata", "Data0001.CSV", package = "MS.Analysis")
  result <- readLines(demoFile, n = 10597)
  result <- readChromatogram.AgilentExport.memory(result)()
  expect_equal(nrow(result$data), 10595)
  expect_equal(as.character(min(result$data$rt)), "0.041")
  expect_equal(as.character(max(result$data$rt)), "35")
  expect_equal(as.character(min(result$data$intensity)), "394975")
  expect_equal(as.character(max(result$data$intensity)), "90985304")
  expect_equal(result$info$source, "Agilent")
  expect_equal(result$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  result <- readLines(demoFile, n = 10597)
  result <- readChromatogram.AgilentExport.memory(result,
                                                  translateComment = chromatogramInfo.AgilentExport)()
  expect_equal(nrow(result$data), 10595)
  expect_equal(as.character(min(result$data$rt)), "0.041")
  expect_equal(as.character(max(result$data$rt)), "35")
  expect_equal(as.character(min(result$data$intensity)), "394975")
  expect_equal(as.character(max(result$data$intensity)), "90985304")
  expect_equal(length(result$info), 9)
  expect_equal(result$info$source, "Agilent")
  expect_equal(result$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(result$info$polarity, "+")
  expect_equal(result$info$signal, "ESI")
  expect_equal(result$info$scan, "TIC")
  expect_equal(result$info$mz, as.numeric(NA))
  expect_equal(result$info$MS, "Scan")
  expect_equal(result$info$fragmentor, 125)
  expect_equal(result$info$filename, "Data0001.d")
})
