
test_that("readData works", {
  result <- readData(dataFrame = datasets::mtcars)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_identical(result$data, datasets::mtcars)
  expect_length(result[["info"]], 1)
  expect_equal(names(result[["info"]]), "source")
  expect_equal(result[["info"]][["source"]], "data")
})

test_that("readDataFrame works", {
  result <- readDataFrame(dataFrame = list(datasets::mtcars, datasets::iris))
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[2]], 2)
  expect_identical(result[[1]]$data, datasets::mtcars)
  expect_length(result[[1]]$info, 1)
  expect_equal(names(result[[1]]$info), "source")
  expect_equal(result[[1]]$info$source, "data")
  expect_identical(result[[2]]$data, datasets::iris)
  expect_equal(names(result[[2]]$info), "source")
  expect_equal(result[[2]]$info$source, "data")
})

test_that("readExcel works", {
  demoExcelFile <- system.file("demoFiles/mtcars.xlsx", package = "XLConnect")
  result <- readExcel(demoExcelFile)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_length(result[["info"]], 2)
  expect_equal(names(result[["info"]]), c("source", "filename"))
  expect_equal(result[["info"]][["source"]], "xlsx")
  result <- readExcel(demoExcelFile, rowNames = rownames(datasets::mtcars))()
  expect_identical(result$data, datasets::mtcars)
})

test_that("readChromatogram.Thermo works", {
  demoRaw <- fs::path_package("extdata", "reserpine07.RAW", package = "MS.Analysis")
  result <- readChromatogram.Thermo(filename = demoRaw, type = "tic", filter = "ms2")
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 1)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 6)
  expect_equal(names(result[[1]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(result[[1]]$info$source, "thermo")
  demoRaw <- fs::path_package("extdata", "reserpine07.RAW", package = "MS.Analysis")
  result <- readChromatogram.Thermo(filename = demoRaw, type = "xic", filter = "ms2",
                                    mz = c(397.16, 448.13), tolerance = 500)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_length(result[[1]]$info, 6)
  expect_equal(names(result[[1]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(result[[1]]$info$source, "thermo")
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_length(result[[1]][["info"]], 6)
  expect_equal(names(result[[1]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(as.character(result[[1]]$info$mz), "397.16")
  expect_equal(names(result[[1]]$data), c("rt", "intensity"))
  expect_equal(nrow(result[[1]]$data), 403)
  expect_equal(as.character(min(result[[1]]$data[,1])), "0.009")
  expect_equal(as.character(max(result[[1]]$data[,1])), "7.00066666666667")
  expect_equal(as.character(min(result[[1]]$data[,2])), "0")
  expect_equal(as.character(max(result[[1]]$data[,2])), "5968176")
  expect_length(result[[2]][["info"]], 6)
  expect_equal(names(result[[2]]$info), c("source", "filename", "mz",
                                          "tolerance", "filter", "type"))
  expect_equal(as.character(result[[2]]$info$mz), "448.13")
  expect_equal(names(result[[2]]$data), c("rt", "intensity"))
  expect_equal(nrow(result[[2]]$data), 403)
  expect_equal(as.character(min(result[[2]]$data[,1])), "0.009")
  expect_equal(as.character(max(result[[2]]$data[,1])), "7.00066666666667")
  expect_equal(as.character(min(result[[2]]$data[,2])), "0")
  expect_equal(as.character(max(result[[2]]$data[,2])), "4614730")
})
