test_that("chromatogramInfo.AgilentExport", {
  result <- chromatogramInfo.AgilentExport("+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "TIC")
  expect_equal(result[1,4], as.numeric(NA))
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("+ESI EIC(372.8974) Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "EIC")
  expect_equal(as.character(result[1,4]), "372.8974")
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("DAD1 - A:Sig=280.0,4.0  Ref=550.0,100.0 Data0001.d")
  expect_equal(names(result), c('signal','scan','wavelength','filename'))
  expect_equal(result[1,1], "DAD1")
  expect_equal(result[1,2], "A:Sig=280.0,4.0")
  expect_equal(as.character(result[1,3]), "280")
  expect_equal(result[1,4], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("BinPump1 - A: Pressure Data0001.d")
  expect_equal(names(result), c('signal','scan','filename'))
  expect_equal(result[1,1], "BinPump1")
  expect_equal(result[1,2], "Pressure")
  expect_equal(result[1,3], "Data0001.d")
})
