
test_that("readData works", {
  result <- readData(dataFrame = datasets::mtcars)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_identical(result$data, datasets::mtcars)
  expect_length(result[["info"]], 1)
  expect_equal(names(result[["info"]]), "source")
  expect_equal(result[["info"]][["source"]], "data")
})

test_that("readDataFrame works", {
  result <- readDataFrame(dataFrame = list(datasets::mtcars, datasets::iris))
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[1]], 2)
  expect_equal(class(result[[1]]), "list")
  expect_length(result[[2]], 2)
  expect_identical(result[[1]]$data, datasets::mtcars)
  expect_length(result[[1]]$info, 1)
  expect_equal(names(result[[1]]$info), "source")
  expect_equal(result[[1]]$info$source, "data")
  expect_identical(result[[2]]$data, datasets::iris)
  expect_equal(names(result[[2]]$info), "source")
  expect_equal(result[[2]]$info$source, "data")
})

test_that("readExcel works", {
  demoExcelFile <- system.file("demoFiles/mtcars.xlsx", package = "XLConnect")
  result <- readExcel(demoExcelFile)
  expect_equal(class(result), "function")
  result <- result()
  expect_equal(class(result), "list")
  expect_length(result, 2)
  expect_length(result[["info"]], 2)
  expect_equal(names(result[["info"]]), c("source", "filename"))
  expect_equal(result[["info"]][["source"]], "xlsx")
  result <- readExcel(demoExcelFile, rowNames = rownames(datasets::mtcars))()
  expect_identical(result$data, datasets::mtcars)
})
