test_that("chromatogramInfo.AgilentExport works", {
  result <- chromatogramInfo.AgilentExport("+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "TIC")
  expect_equal(result[1,4], as.numeric(NA))
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("+ESI EIC(485.6975) Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "EIC")
  expect_equal(as.character(result[1,4]), "485.6975")
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("DAD1 - A:Sig=280.0,4.0  Ref=550.0,100.0 Data0001.d")
  expect_equal(names(result), c('signal','scan','wavelength','filename'))
  expect_equal(result[1,1], "DAD1")
  expect_equal(result[1,2], "A:Sig=280.0,4.0")
  expect_equal(as.character(result[1,3]), "280")
  expect_equal(result[1,4], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("BinPump1 - A: Pressure Data0001.d")
  expect_equal(names(result), c('signal','scan','filename'))
  expect_equal(result[1,1], "BinPump1")
  expect_equal(result[1,2], "Pressure")
  expect_equal(result[1,3], "Data0001.d")
})

test_that("readChromatogram.AgilentExport.memory works", {
  demoFile <- fs::path_package("extdata", "Data0001.CSV", package = "MS.Analysis")
  result <- readLines(demoFile, n = 10597)
  result <- readChromatogram.AgilentExport.memory(result)()
  expect_equal(nrow(result$data), 10595)
  expect_equal(as.character(min(result$data$rt)), "0.041")
  expect_equal(as.character(max(result$data$rt)), "35")
  expect_equal(as.character(min(result$data$intensity)), "394975")
  expect_equal(as.character(max(result$data$intensity)), "90985304")
  expect_equal(result$info$source, "Agilent")
  expect_equal(result$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  result <- readLines(demoFile, n = 10597)
  result <- readChromatogram.AgilentExport.memory(result,
                                                  translateComment = chromatogramInfo.AgilentExport)()
  expect_equal(nrow(result$data), 10595)
  expect_equal(as.character(min(result$data$rt)), "0.041")
  expect_equal(as.character(max(result$data$rt)), "35")
  expect_equal(as.character(min(result$data$intensity)), "394975")
  expect_equal(as.character(max(result$data$intensity)), "90985304")
  expect_equal(length(result$info), 9)
  expect_equal(result$info$source, "Agilent")
  expect_equal(result$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(result$info$polarity, "+")
  expect_equal(result$info$signal, "ESI")
  expect_equal(result$info$scan, "TIC")
  expect_equal(result$info$mz, as.numeric(NA))
  expect_equal(result$info$MS, "Scan")
  expect_equal(result$info$fragmentor, 125)
  expect_equal(result$info$filename, "Data0001.d")
})

test_that("readChromatogram.AgilentExport works", {
  demoFile <- fs::path_package("extdata", "Data0001.CSV", package = "MS.Analysis")
  result <- readChromatogram.AgilentExport(demoFile, translateComment = chromatogramInfo.AgilentExport)()
  expect_length(result, 8)
  infoResult <- purrr::map_df(result, ~as.data.frame(.x$info))
  expect_equal(dim(infoResult), c( 8, 10))
  expect_equal(colnames(infoResult), c('source', 'comment', 'polarity', 'signal',
                                       'scan', 'mz', 'MS', 'fragmentor', 'filename',
                                       'wavelength'))
  expect_equal(infoResult$scan , c('TIC', 'BPC', 'EIC', 'EIC', 'C:Sig=214.0,4.0',
                                   'Pressure', 'Flow', 'Solvent Ratio B'))
  expect_equal(nrow(result[[1]]$data), 10595)
  expect_equal(as.character(min(result[[1]]$data$rt)), "0.041")
  expect_equal(as.character(max(result[[1]]$data$rt)), "35")
  expect_equal(as.character(min(result[[1]]$data$intensity)), "394975")
  expect_equal(as.character(max(result[[1]]$data$intensity)), "90985304")
  expect_equal(length(result[[1]]$info), 9)
  expect_equal(result[[1]]$info$source, "Agilent")
  expect_equal(result[[1]]$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(result[[1]]$info$polarity, "+")
  expect_equal(result[[1]]$info$signal, "ESI")
  expect_equal(result[[1]]$info$scan, "TIC")
  expect_equal(result[[1]]$info$mz, as.numeric(NA))
  expect_equal(result[[1]]$info$MS, "Scan")
  expect_equal(result[[1]]$info$fragmentor, 125)
  expect_equal(result[[1]]$info$filename, "Data0001.d")
  expect_equal(nrow(result[[3]]$data), 10595)
  expect_equal(as.character(min(result[[3]]$data$rt)), "0.041")
  expect_equal(as.character(max(result[[3]]$data$rt)), "35")
  expect_equal(as.character(min(result[[3]]$data$intensity)), "0")
  expect_equal(as.character(max(result[[3]]$data$intensity)), "472341")
  expect_equal(length(result[[3]]$info), 9)
  expect_equal(result[[3]]$info$source, "Agilent")
  expect_equal(result[[3]]$info$comment, "+ESI EIC(465.6025) Scan Frag=125.0V Data0001.d ")
  expect_equal(result[[3]]$info$polarity, "+")
  expect_equal(result[[3]]$info$signal, "ESI")
  expect_equal(result[[3]]$info$scan, "EIC")
  expect_equal(as.character(result[[3]]$info$mz), "465.6025")
  expect_equal(result[[3]]$info$MS, "Scan")
  expect_equal(result[[3]]$info$fragmentor, 125)
  expect_equal(result[[3]]$info$filename, "Data0001.d")
})
